# https://openapi-generator.tech/docs/usage/#generate
apiPackage: Api
gitRepoId: mydhl
gitUserId: spysystem
invokerPackage: MyDHL
modelPackage: Model
composerVendorName: spysystem
composerProjectName: mydhl
