<?php
/**
 * AddressModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

/**
 * AddressModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressModelAttributes
{
    public string $strStreetLines = 'street_lines';
    public string $strStreetName = 'street_name';
    public string $strBuildingName = 'building_name';
    public string $strStreetNumber = 'street_number';
    public string $strStreetLines2 = 'street_lines2';
    public string $strStreetLines3 = 'street_lines3';
    public string $strCity = 'city';
    public string $strStateOrProvinceCode = 'state_or_province_code';
    public string $strPostalCode = 'postal_code';
    public string $strCountryCode = 'country_code';
    public string $strSuburb = 'suburb';
}

