<?php
/**
 * AddressModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

/**
 * AddressModelFields Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressModelFields
{
    public string $strStreetLines = 'StreetLines';
    public string $strStreetName = 'StreetName';
    public string $strBuildingName = 'BuildingName';
    public string $strStreetNumber = 'StreetNumber';
    public string $strStreetLines2 = 'StreetLines2';
    public string $strStreetLines3 = 'StreetLines3';
    public string $strCity = 'City';
    public string $strStateOrProvinceCode = 'StateOrProvinceCode';
    public string $strPostalCode = 'PostalCode';
    public string $strCountryCode = 'CountryCode';
    public string $strSuburb = 'Suburb';
}

