<?php
/**
 * Billing
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

use \ArrayAccess;
use \MyDHL\ObjectSerializer;

/**
 * Billing Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Billing implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Billing';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'shipper_account_number' => 'string',
        'shipping_payment_type' => 'string',
        'billing_account_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'shipper_account_number' => null,
        'shipping_payment_type' => null,
        'billing_account_number' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shipper_account_number' => 'ShipperAccountNumber',
        'shipping_payment_type' => 'ShippingPaymentType',
        'billing_account_number' => 'BillingAccountNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shipper_account_number' => 'setShipperAccountNumber',
        'shipping_payment_type' => 'setShippingPaymentType',
        'billing_account_number' => 'setBillingAccountNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shipper_account_number' => 'getShipperAccountNumber',
        'shipping_payment_type' => 'getShippingPaymentType',
        'billing_account_number' => 'getBillingAccountNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipper_account_number'] = isset($data['shipper_account_number']) ? $data['shipper_account_number'] : null;
        $this->container['shipping_payment_type'] = isset($data['shipping_payment_type']) ? $data['shipping_payment_type'] : null;
        $this->container['billing_account_number'] = isset($data['billing_account_number']) ? $data['billing_account_number'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shipper_account_number'] === null) {
            $invalidProperties[] = "'shipper_account_number' can't be null";
        }
        if ($this->container['shipping_payment_type'] === null) {
            $invalidProperties[] = "'shipping_payment_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipper_account_number
     *
     * @return string
     */
    public function getShipperAccountNumber()
    {
        return $this->container['shipper_account_number'];
    }

    /**
     * Sets shipper_account_number
     *
     * @param string $shipper_account_number shipper_account_number
     *
     * @return $this
     */
    public function setShipperAccountNumber($shipper_account_number)
    {
        $this->container['shipper_account_number'] = $shipper_account_number;

        return $this;
    }

    /**
     * Gets shipping_payment_type
     *
     * @return string
     */
    public function getShippingPaymentType()
    {
        return $this->container['shipping_payment_type'];
    }

    /**
     * Sets shipping_payment_type
     *
     * @param string $shipping_payment_type shipping_payment_type
     *
     * @return $this
     */
    public function setShippingPaymentType($shipping_payment_type)
    {
        $this->container['shipping_payment_type'] = $shipping_payment_type;

        return $this;
    }

    /**
     * Gets billing_account_number
     *
     * @return string|null
     */
    public function getBillingAccountNumber()
    {
        return $this->container['billing_account_number'];
    }

    /**
     * Sets billing_account_number
     *
     * @param string|null $billing_account_number billing_account_number
     *
     * @return $this
     */
    public function setBillingAccountNumber($billing_account_number)
    {
        $this->container['billing_account_number'] = $billing_account_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


