<?php
/**
 * LabelOptions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

use \ArrayAccess;
use \MyDHL\ObjectSerializer;

/**
 * LabelOptions Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LabelOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return LabelOptionsModelFields
      */
    public static function GetModelFields(): LabelOptionsModelFields
    {
        return new LabelOptionsModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return LabelOptionsModelAttributes
      */
    public static function GetModelAttributes(): LabelOptionsModelAttributes
    {
        return new LabelOptionsModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LabelOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'printer_dpi' => 'string',
        'hide_account_in_waybill_document' => 'string',
        'request_waybill_document' => 'string',
        'number_of_waybill_document_copies' => 'int',
        'request_dhl_customs_invoice' => 'string',
        'dhl_customs_invoice_language' => 'string',
        'dhl_customs_invoice_type' => 'string',
        'request_shipment_receipt' => 'string',
        'customer_logo' => '\MyDHL\Model\CustomerLogo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'printer_dpi' => null,
        'hide_account_in_waybill_document' => null,
        'request_waybill_document' => null,
        'number_of_waybill_document_copies' => null,
        'request_dhl_customs_invoice' => null,
        'dhl_customs_invoice_language' => null,
        'dhl_customs_invoice_type' => null,
        'request_shipment_receipt' => null,
        'customer_logo' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'printer_dpi' => false,
		'hide_account_in_waybill_document' => false,
		'request_waybill_document' => false,
		'number_of_waybill_document_copies' => false,
		'request_dhl_customs_invoice' => false,
		'dhl_customs_invoice_language' => false,
		'dhl_customs_invoice_type' => false,
		'request_shipment_receipt' => false,
		'customer_logo' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'printer_dpi' => 'PrinterDPI',
        'hide_account_in_waybill_document' => 'HideAccountInWaybillDocument',
        'request_waybill_document' => 'RequestWaybillDocument',
        'number_of_waybill_document_copies' => 'NumberOfWaybillDocumentCopies',
        'request_dhl_customs_invoice' => 'RequestDHLCustomsInvoice',
        'dhl_customs_invoice_language' => 'DHLCustomsInvoiceLanguage',
        'dhl_customs_invoice_type' => 'DHLCustomsInvoiceType',
        'request_shipment_receipt' => 'RequestShipmentReceipt',
        'customer_logo' => 'CustomerLogo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'printer_dpi' => 'setPrinterDpi',
        'hide_account_in_waybill_document' => 'setHideAccountInWaybillDocument',
        'request_waybill_document' => 'setRequestWaybillDocument',
        'number_of_waybill_document_copies' => 'setNumberOfWaybillDocumentCopies',
        'request_dhl_customs_invoice' => 'setRequestDhlCustomsInvoice',
        'dhl_customs_invoice_language' => 'setDhlCustomsInvoiceLanguage',
        'dhl_customs_invoice_type' => 'setDhlCustomsInvoiceType',
        'request_shipment_receipt' => 'setRequestShipmentReceipt',
        'customer_logo' => 'setCustomerLogo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'printer_dpi' => 'getPrinterDpi',
        'hide_account_in_waybill_document' => 'getHideAccountInWaybillDocument',
        'request_waybill_document' => 'getRequestWaybillDocument',
        'number_of_waybill_document_copies' => 'getNumberOfWaybillDocumentCopies',
        'request_dhl_customs_invoice' => 'getRequestDhlCustomsInvoice',
        'dhl_customs_invoice_language' => 'getDhlCustomsInvoiceLanguage',
        'dhl_customs_invoice_type' => 'getDhlCustomsInvoiceType',
        'request_shipment_receipt' => 'getRequestShipmentReceipt',
        'customer_logo' => 'getCustomerLogo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const REQUEST_DHL_CUSTOMS_INVOICE_Y = 'Y';
    public const REQUEST_DHL_CUSTOMS_INVOICE_N = 'N';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_ENG = 'eng';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_BUL = 'bul';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_CZE = 'cze';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_DAN = 'dan';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_GER = 'ger';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_GRE = 'gre';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_EST = 'est';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_FIN = 'fin';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_FRE = 'fre';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_HUN = 'hun';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_ICE = 'ice';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_ITA = 'ita';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_LIT = 'lit';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_LAV = 'lav';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_DUT = 'dut';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_NNO = 'nno';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_POL = 'pol';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_POR = 'por';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_RUM = 'rum';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_SLV = 'slv';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_SLP = 'slp';
    public const DHL_CUSTOMS_INVOICE_LANGUAGE_SPA = 'spa';
    public const DHL_CUSTOMS_INVOICE_TYPE_COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE';
    public const DHL_CUSTOMS_INVOICE_TYPE_PROFORMA_INVOICE = 'PROFORMA_INVOICE';
    public const REQUEST_SHIPMENT_RECEIPT_Y = 'Y';
    public const REQUEST_SHIPMENT_RECEIPT_N = 'N';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRequestDhlCustomsInvoiceAllowableValues()
    {
        return [
            self::REQUEST_DHL_CUSTOMS_INVOICE_Y,
            self::REQUEST_DHL_CUSTOMS_INVOICE_N,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDhlCustomsInvoiceLanguageAllowableValues()
    {
        return [
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_ENG,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_BUL,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_CZE,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_DAN,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_GER,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_GRE,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_EST,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_FIN,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_FRE,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_HUN,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_ICE,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_ITA,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_LIT,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_LAV,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_DUT,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_NNO,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_POL,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_POR,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_RUM,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_SLV,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_SLP,
            self::DHL_CUSTOMS_INVOICE_LANGUAGE_SPA,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDhlCustomsInvoiceTypeAllowableValues()
    {
        return [
            self::DHL_CUSTOMS_INVOICE_TYPE_COMMERCIAL_INVOICE,
            self::DHL_CUSTOMS_INVOICE_TYPE_PROFORMA_INVOICE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRequestShipmentReceiptAllowableValues()
    {
        return [
            self::REQUEST_SHIPMENT_RECEIPT_Y,
            self::REQUEST_SHIPMENT_RECEIPT_N,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('printer_dpi', $data ?? [], null);
        $this->setIfExists('hide_account_in_waybill_document', $data ?? [], null);
        $this->setIfExists('request_waybill_document', $data ?? [], null);
        $this->setIfExists('number_of_waybill_document_copies', $data ?? [], null);
        $this->setIfExists('request_dhl_customs_invoice', $data ?? [], null);
        $this->setIfExists('dhl_customs_invoice_language', $data ?? [], null);
        $this->setIfExists('dhl_customs_invoice_type', $data ?? [], null);
        $this->setIfExists('request_shipment_receipt', $data ?? [], null);
        $this->setIfExists('customer_logo', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRequestDhlCustomsInvoiceAllowableValues();
        if (!is_null($this->container['request_dhl_customs_invoice']) && !in_array($this->container['request_dhl_customs_invoice'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'request_dhl_customs_invoice', must be one of '%s'",
                $this->container['request_dhl_customs_invoice'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDhlCustomsInvoiceLanguageAllowableValues();
        if (!is_null($this->container['dhl_customs_invoice_language']) && !in_array($this->container['dhl_customs_invoice_language'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'dhl_customs_invoice_language', must be one of '%s'",
                $this->container['dhl_customs_invoice_language'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDhlCustomsInvoiceTypeAllowableValues();
        if (!is_null($this->container['dhl_customs_invoice_type']) && !in_array($this->container['dhl_customs_invoice_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'dhl_customs_invoice_type', must be one of '%s'",
                $this->container['dhl_customs_invoice_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getRequestShipmentReceiptAllowableValues();
        if (!is_null($this->container['request_shipment_receipt']) && !in_array($this->container['request_shipment_receipt'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'request_shipment_receipt', must be one of '%s'",
                $this->container['request_shipment_receipt'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets printer_dpi
     *
     * @return string|null
     */
    public function getPrinterDpi()
    {
        return $this->container['printer_dpi'];
    }

    /**
     * Sets printer_dpi
     *
     * @param string|null $printer_dpi printer_dpi
     *
     * @return self
     */
    public function setPrinterDpi($printer_dpi)
    {

        if (is_null($printer_dpi)) {
            throw new \InvalidArgumentException('non-nullable printer_dpi cannot be null');
        }

        $this->container['printer_dpi'] = $printer_dpi;

        return $this;
    }

    /**
     * Gets hide_account_in_waybill_document
     *
     * @return string|null
     */
    public function getHideAccountInWaybillDocument()
    {
        return $this->container['hide_account_in_waybill_document'];
    }

    /**
     * Sets hide_account_in_waybill_document
     *
     * @param string|null $hide_account_in_waybill_document hide_account_in_waybill_document
     *
     * @return self
     */
    public function setHideAccountInWaybillDocument($hide_account_in_waybill_document)
    {

        if (is_null($hide_account_in_waybill_document)) {
            throw new \InvalidArgumentException('non-nullable hide_account_in_waybill_document cannot be null');
        }

        $this->container['hide_account_in_waybill_document'] = $hide_account_in_waybill_document;

        return $this;
    }

    /**
     * Gets request_waybill_document
     *
     * @return string|null
     */
    public function getRequestWaybillDocument()
    {
        return $this->container['request_waybill_document'];
    }

    /**
     * Sets request_waybill_document
     *
     * @param string|null $request_waybill_document request_waybill_document
     *
     * @return self
     */
    public function setRequestWaybillDocument($request_waybill_document)
    {

        if (is_null($request_waybill_document)) {
            throw new \InvalidArgumentException('non-nullable request_waybill_document cannot be null');
        }

        $this->container['request_waybill_document'] = $request_waybill_document;

        return $this;
    }

    /**
     * Gets number_of_waybill_document_copies
     *
     * @return int|null
     */
    public function getNumberOfWaybillDocumentCopies()
    {
        return $this->container['number_of_waybill_document_copies'];
    }

    /**
     * Sets number_of_waybill_document_copies
     *
     * @param int|null $number_of_waybill_document_copies number_of_waybill_document_copies
     *
     * @return self
     */
    public function setNumberOfWaybillDocumentCopies($number_of_waybill_document_copies)
    {

        if (is_null($number_of_waybill_document_copies)) {
            throw new \InvalidArgumentException('non-nullable number_of_waybill_document_copies cannot be null');
        }

        $this->container['number_of_waybill_document_copies'] = $number_of_waybill_document_copies;

        return $this;
    }

    /**
     * Gets request_dhl_customs_invoice
     *
     * @return string|null
     */
    public function getRequestDhlCustomsInvoice()
    {
        return $this->container['request_dhl_customs_invoice'];
    }

    /**
     * Sets request_dhl_customs_invoice
     *
     * @param string|null $request_dhl_customs_invoice request_dhl_customs_invoice
     *
     * @return self
     */
    public function setRequestDhlCustomsInvoice($request_dhl_customs_invoice)
    {
        $allowedValues = $this->getRequestDhlCustomsInvoiceAllowableValues();
        if (!is_null($request_dhl_customs_invoice) && !in_array($request_dhl_customs_invoice, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'request_dhl_customs_invoice', must be one of '%s'",
                    $request_dhl_customs_invoice,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($request_dhl_customs_invoice)) {
            throw new \InvalidArgumentException('non-nullable request_dhl_customs_invoice cannot be null');
        }

        $this->container['request_dhl_customs_invoice'] = $request_dhl_customs_invoice;

        return $this;
    }

    /**
     * Gets dhl_customs_invoice_language
     *
     * @return string|null
     */
    public function getDhlCustomsInvoiceLanguage()
    {
        return $this->container['dhl_customs_invoice_language'];
    }

    /**
     * Sets dhl_customs_invoice_language
     *
     * @param string|null $dhl_customs_invoice_language dhl_customs_invoice_language
     *
     * @return self
     */
    public function setDhlCustomsInvoiceLanguage($dhl_customs_invoice_language)
    {
        $allowedValues = $this->getDhlCustomsInvoiceLanguageAllowableValues();
        if (!is_null($dhl_customs_invoice_language) && !in_array($dhl_customs_invoice_language, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'dhl_customs_invoice_language', must be one of '%s'",
                    $dhl_customs_invoice_language,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($dhl_customs_invoice_language)) {
            throw new \InvalidArgumentException('non-nullable dhl_customs_invoice_language cannot be null');
        }

        $this->container['dhl_customs_invoice_language'] = $dhl_customs_invoice_language;

        return $this;
    }

    /**
     * Gets dhl_customs_invoice_type
     *
     * @return string|null
     */
    public function getDhlCustomsInvoiceType()
    {
        return $this->container['dhl_customs_invoice_type'];
    }

    /**
     * Sets dhl_customs_invoice_type
     *
     * @param string|null $dhl_customs_invoice_type dhl_customs_invoice_type
     *
     * @return self
     */
    public function setDhlCustomsInvoiceType($dhl_customs_invoice_type)
    {
        $allowedValues = $this->getDhlCustomsInvoiceTypeAllowableValues();
        if (!is_null($dhl_customs_invoice_type) && !in_array($dhl_customs_invoice_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'dhl_customs_invoice_type', must be one of '%s'",
                    $dhl_customs_invoice_type,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($dhl_customs_invoice_type)) {
            throw new \InvalidArgumentException('non-nullable dhl_customs_invoice_type cannot be null');
        }

        $this->container['dhl_customs_invoice_type'] = $dhl_customs_invoice_type;

        return $this;
    }

    /**
     * Gets request_shipment_receipt
     *
     * @return string|null
     */
    public function getRequestShipmentReceipt()
    {
        return $this->container['request_shipment_receipt'];
    }

    /**
     * Sets request_shipment_receipt
     *
     * @param string|null $request_shipment_receipt request_shipment_receipt
     *
     * @return self
     */
    public function setRequestShipmentReceipt($request_shipment_receipt)
    {
        $allowedValues = $this->getRequestShipmentReceiptAllowableValues();
        if (!is_null($request_shipment_receipt) && !in_array($request_shipment_receipt, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'request_shipment_receipt', must be one of '%s'",
                    $request_shipment_receipt,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($request_shipment_receipt)) {
            throw new \InvalidArgumentException('non-nullable request_shipment_receipt cannot be null');
        }

        $this->container['request_shipment_receipt'] = $request_shipment_receipt;

        return $this;
    }

    /**
     * Gets customer_logo
     *
     * @return \MyDHL\Model\CustomerLogo|null
     */
    public function getCustomerLogo()
    {
        return $this->container['customer_logo'];
    }

    /**
     * Sets customer_logo
     *
     * @param \MyDHL\Model\CustomerLogo|null $customer_logo customer_logo
     *
     * @return self
     */
    public function setCustomerLogo($customer_logo)
    {

        if (is_null($customer_logo)) {
            throw new \InvalidArgumentException('non-nullable customer_logo cannot be null');
        }

        $this->container['customer_logo'] = $customer_logo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


