<?php
/**
 * RateRequestRequestedShipmentModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

/**
 * RateRequestRequestedShipmentModelFields Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RateRequestRequestedShipmentModelFields
{
    public string $strGetRateEstimates = 'GetRateEstimates';
    public string $strGetDetailedRateBreakdown = 'GetDetailedRateBreakdown';
    public string $strIncludeAdditionalCurrencies = 'IncludeAdditionalCurrencies';
    public string $strDropOffType = 'DropOffType';
    public string $strNextBusinessDay = 'NextBusinessDay';
    public string $strShipTimestamp = 'ShipTimestamp';
    public string $strPickupLocationCloseTime = 'PickupLocationCloseTime';
    public string $strUnitOfMeasurement = 'UnitOfMeasurement';
    public string $strContent = 'Content';
    public string $strDeclaredValue = 'DeclaredValue';
    public string $strDeclaredValueCurrecyCode = 'DeclaredValueCurrecyCode';
    public string $strPaymentInfo = 'PaymentInfo';
    public string $strAccount = 'Account';
    public string $strPayerCountryCode = 'PayerCountryCode';
    public string $strRequestValueAddedService = 'RequestValueAddedService';
    public string $strServiceType = 'ServiceType';
    public string $strNetworkTypeCode = 'NetworkTypeCode';
    public string $strCustomerAggrementInd = 'CustomerAggrementInd';
    public string $strValidateReadyTime = 'ValidateReadyTime';
    public string $strShip = 'Ship';
    public string $strPackages = 'Packages';
    public string $strBilling = 'Billing';
    public string $strSpecialServices = 'SpecialServices';
}

