<?php
/**
 * RequestedShipmentModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

/**
 * RequestedShipmentModelFields Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RequestedShipmentModelFields
{
    public string $strShipTimestamp = 'ShipTimestamp';
    public string $strPickupLocationCloseTime = 'PickupLocationCloseTime';
    public string $strSpecialPickupInstruction = 'SpecialPickupInstruction';
    public string $strPickupLocation = 'PickupLocation';
    public string $strPaymentInfo = 'PaymentInfo';
    public string $strOnDemandDeliveryUrlRequest = 'OnDemandDeliveryURLRequest';
    public string $strGetRateEstimates = 'GetRateEstimates';
    public string $strShipmentInfo = 'ShipmentInfo';
    public string $strInternationalDetail = 'InternationalDetail';
    public string $strOnDemandDeliveryOptions = 'OnDemandDeliveryOptions';
    public string $strShip = 'Ship';
    public string $strPackages = 'Packages';
    public string $strShipmentNotifications = 'ShipmentNotifications';
    public string $strDeclaredValue = 'DeclaredValue';
    public string $strDeclaredValueCurrecyCode = 'DeclaredValueCurrecyCode';
}

