<?php
/**
 * ServiceModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

/**
 * ServiceModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceModelAttributes
{
    public string $strAtType = 'at_type';
    public string $strDeliveryTime = 'delivery_time';
    public string $strDeliveryType = 'delivery_type';
    public string $strCutoffTime = 'cutoff_time';
    public string $strCutoffTimeGmt = 'cutoff_time_gmt';
    public string $strCutoffTimeOffset = 'cutoff_time_offset';
    public string $strNextBusinessDayInd = 'next_business_day_ind';
    public string $strPickupWindowEarliestTime = 'pickup_window_earliest_time';
    public string $strPickupWindowLatestTime = 'pickup_window_latest_time';
    public string $strServiceName = 'service_name';
    public string $strLocalServiceType = 'local_service_type';
    public string $strLocalServiceCountryCode = 'local_service_country_code';
    public string $strNetworkTypeCode = 'network_type_code';
    public string $strCustomerAggreementInd = 'customer_aggreement_ind';
    public string $strTotalTransitDays = 'total_transit_days';
    public string $strPickupAdditionalDates = 'pickup_additional_dates';
    public string $strDeliveryAdditionalDays = 'delivery_additional_days';
    public string $strVolumetricWeight = 'volumetric_weight';
    public string $strQuotedWeight = 'quoted_weight';
    public string $strUnitOfMeasurement = 'unit_of_measurement';
    public string $strPickupDayOfWeek = 'pickup_day_of_week';
    public string $strDestinationDayOfWeek = 'destination_day_of_week';
    public string $strPricingDate = 'pricing_date';
    public string $strOriginServiceArea = 'origin_service_area';
    public string $strDestinationServiceArea = 'destination_service_area';
    public string $strCharges = 'charges';
    public string $strTotalChargeTypes = 'total_charge_types';
}

