<?php
/**
 * SupermodelIoLogisticsExpressLandedCostRequestModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.  Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * The version of the OpenAPI document: 2.7.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyDHL\Model;

/**
 * SupermodelIoLogisticsExpressLandedCostRequestModelFields Class Doc Comment
 *
 * @category Class
 * @description Landed cost request model description
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupermodelIoLogisticsExpressLandedCostRequestModelFields
{
    public string $strCustomerDetails = 'customerDetails';
    public string $strAccounts = 'accounts';
    public string $strProductCode = 'productCode';
    public string $strLocalProductCode = 'localProductCode';
    public string $strUnitOfMeasurement = 'unitOfMeasurement';
    public string $strCurrencyCode = 'currencyCode';
    public string $strIsCustomsDeclarable = 'isCustomsDeclarable';
    public string $strIsDtpRequested = 'isDTPRequested';
    public string $strIsInsuranceRequested = 'isInsuranceRequested';
    public string $strGetCostBreakdown = 'getCostBreakdown';
    public string $strCharges = 'charges';
    public string $strShipmentPurpose = 'shipmentPurpose';
    public string $strTransportationMode = 'transportationMode';
    public string $strMerchantSelectedCarrierName = 'merchantSelectedCarrierName';
    public string $strPackages = 'packages';
    public string $strItems = 'items';
    public string $strGetTariffFormula = 'getTariffFormula';
    public string $strGetQuotationId = 'getQuotationID';
}

