<?php
/**
 * ExportLineItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyDHL;

use PHPUnit\Framework\TestCase;

/**
 * ExportLineItemTest Class Doc Comment
 *
 * @category    Class
 * @description ExportLineItem
 * @package     MyDHL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExportLineItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExportLineItem"
     */
    public function testExportLineItem()
    {
    }

    /**
     * Test attribute "commodity_code"
     */
    public function testPropertyCommodityCode()
    {
    }

    /**
     * Test attribute "eccn"
     */
    public function testPropertyEccn()
    {
    }

    /**
     * Test attribute "export_reason_type"
     */
    public function testPropertyExportReasonType()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "quantity_unit_of_measurement"
     */
    public function testPropertyQuantityUnitOfMeasurement()
    {
    }

    /**
     * Test attribute "item_description"
     */
    public function testPropertyItemDescription()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "net_weight"
     */
    public function testPropertyNetWeight()
    {
    }

    /**
     * Test attribute "gross_weight"
     */
    public function testPropertyGrossWeight()
    {
    }

    /**
     * Test attribute "manufacturing_country_code"
     */
    public function testPropertyManufacturingCountryCode()
    {
    }
}
