<?php
/**
 * ShipTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyDHL;

use PHPUnit\Framework\TestCase;

/**
 * ShipTest Class Doc Comment
 *
 * @category    Class
 * @description Ship
 * @package     MyDHL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ship"
     */
    public function testShip()
    {
    }

    /**
     * Test attribute "shipper"
     */
    public function testPropertyShipper()
    {
    }

    /**
     * Test attribute "pickup"
     */
    public function testPropertyPickup()
    {
    }

    /**
     * Test attribute "booking_requestor"
     */
    public function testPropertyBookingRequestor()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {
    }
}
