<?php
/**
 * ShipmentNotificationsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Integration for DHL Express MyDHL Service
 *
 * OpenAPI description for the Integration with MyDHL
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: thomas@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyDHL\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentNotificationsTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentNotifications
 * @package     MyDHL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentNotificationsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentNotifications"
     */
    public function testShipmentNotifications()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipment_notification"
     */
    public function testPropertyShipmentNotification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
