<?php
/**
 * SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MyDHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Express APIs (MyDHL API)
 *
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.  Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments)
 *
 * The version of the OpenAPI document: 2.7.2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyDHL\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInnerTest Class Doc Comment
 *
 * @category    Class
 * @description SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInner
 * @package     MyDHL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInner"
     */
    public function testSupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type_code"
     */
    public function testPropertyTypeCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receiver_id"
     */
    public function testPropertyReceiverId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "language_country_code"
     */
    public function testPropertyLanguageCountryCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bespoke_message"
     */
    public function testPropertyBespokeMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
